name: Telerik-Github-Actions-Practice

on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1

    - name: Run tests
      run: crystal spec

    - name: Run Crystal
      run: |
        crystal hello_world/src/hello_world.cr
    
    - name: Build crystal
      run: |
        # mkdir -p hello_world/out
        # crystal build hello_world/src/hello_world.cr --static --release -o hello_world/out/hello_world
        crystal build hello_world/src/hello_world.cr -o hello_world/out/hello_world

    - uses: actions/upload-artifact@v2
      with:
        name: hello_world
        path: hello_world/out

  notifications:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SSH_SLACK_WEBHOOK }}
        SLACK_CHANNEL: telerik-upskill-devops
        SLACK_USERNAME: shitBot
        SLACK_COLOR: ${{ job.status }}
        SLACK_FOOTER: "You better not know who wrote this :D"
