name: Telerik-Github-Actions-Practice

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Style with pycodestyle
      run: |
        pycodestyle *.py
    - name: Unit testing
      run: |
        python3 -m doctest factorial.py
        steps:
    - name: Adding Known hosts
      run: "rsync -azP TheFile.log1.17-00-47-01-11-2021 gha@ssh.nedko.info:/home/gha/github-actions3/"
      # run: "scp -rC -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/gha/github-actions-$(date +\-%d\-%m\-%y\-%H\-%M\-%S)"
