name: Telerik-Github-Actions-Practice

on: [push]
jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1

    - name: Run tests
      run: crystal spec

    - name: Run Crystal
      run: |
        crystal /home/runner/work/telerik-github-actions-2021/telerik-github-actions-2021/src/game-of-life.cr
        pwd
        ls -lah
    
    - name: Build crystal
      run: |
        crystal /home/runner/work/telerik-github-actions-2021/telerik-github-actions-2021/src/build game-of-life.cr
        pwd
        ls -lah
        ll
