name: pylint magic
on: [push] #we use on on what events we trigger it
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: "python –m pip install –upgrade pip" ; "pip install pylint"
