name: deployment-of-a-python-app
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -run: echo "this ${{ github.event_name }}"
        #     - uses: actions/checkout@v2
        #     - uses: actions/setup-python@v2
        #     - uses: "python –m pip install –upgrade pip" ; "pip install pylint"
